"""empty message

Revision ID: 0ba765ce34bb
Revises: 9200400516ac
Create Date: 2019-05-16 15:01:16.990790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ba765ce34bb'
down_revision = '9200400516ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupings',
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('groupName', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['groupName'], ['groups.groupName'], onupdate='cascade'),
    sa.ForeignKeyConstraint(['title'], ['artwork.title'], onupdate='cascade'),
    sa.PrimaryKeyConstraint('title', 'groupName')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groupings')
    # ### end Alembic commands ###
