"""empty message

Revision ID: 13163bc5929a
Revises: 913a11639815
Create Date: 2019-05-11 07:40:06.781824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13163bc5929a'
down_revision = '913a11639815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupings',
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('groupName', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['groupName'], ['groups.groupName'], onupdate='cascade'),
    sa.ForeignKeyConstraint(['title'], ['artwork.title'], onupdate='cascade')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groupings')
    # ### end Alembic commands ###
