"""empty message

Revision ID: 93f6a033b4c7
Revises: b091d1d587b5
Create Date: 2019-05-08 20:37:02.936063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f6a033b4c7'
down_revision = 'b091d1d587b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artwork', sa.Column('purchased', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artwork', 'purchased')
    # ### end Alembic commands ###
