"""empty message

Revision ID: 9b976e6dc8af
Revises: d3671d4c1a8e
Create Date: 2019-05-11 20:12:37.323704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b976e6dc8af'
down_revision = 'd3671d4c1a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupPreferences',
    sa.Column('customerName', sa.String(length=120), nullable=True),
    sa.Column('groupName', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['customerName'], ['customers.customerName'], ),
    sa.ForeignKeyConstraint(['groupName'], ['groups.groupName'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groupPreferences')
    # ### end Alembic commands ###
