"""empty message

Revision ID: b091d1d587b5
Revises: ef99d3d704d2
Create Date: 2019-05-08 09:17:21.874976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b091d1d587b5'
down_revision = 'ef99d3d704d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grouping')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grouping',
    sa.Column('title', mysql.VARCHAR(collation=u'utf8mb4_general_ci', length=120), nullable=True),
    sa.Column('groupName', mysql.VARCHAR(collation=u'utf8mb4_general_ci', length=60), nullable=True),
    sa.ForeignKeyConstraint(['groupName'], [u'groups.groupName'], name=u'grouping_ibfk_1'),
    sa.ForeignKeyConstraint(['title'], [u'artwork.title'], name=u'grouping_ibfk_2'),
    mysql_collate=u'utf8mb4_general_ci',
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
