"""empty message

Revision ID: bdfa6b92ae46
Revises: f292fa78130f
Create Date: 2019-05-06 01:05:14.930576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdfa6b92ae46'
down_revision = 'f292fa78130f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'artwork_ibfk_2', 'artwork', type_='foreignkey')
    op.drop_column('artwork', 'purchased')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artwork', sa.Column('purchased', mysql.VARCHAR(collation=u'utf8mb4_general_ci', length=120), nullable=False))
    op.create_foreign_key(u'artwork_ibfk_2', 'artwork', 'customers', ['purchased'], ['customerName'])
    # ### end Alembic commands ###
