"""empty message

Revision ID: d3671d4c1a8e
Revises: 5631c688ad2e
Create Date: 2019-05-11 12:08:07.029791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3671d4c1a8e'
down_revision = '5631c688ad2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artwork', sa.Column('purchaser', sa.String(length=120), nullable=True))
    op.create_foreign_key(None, 'artwork', 'customers', ['purchaser'], ['customerName'], onupdate='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artwork', type_='foreignkey')
    op.drop_column('artwork', 'purchaser')
    # ### end Alembic commands ###
