"""empty message

Revision ID: deb1407115f6
Revises: 93f6a033b4c7
Create Date: 2019-05-10 07:22:38.379990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb1407115f6'
down_revision = '93f6a033b4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artStyles',
    sa.Column('artistName', sa.String(length=120), nullable=True),
    sa.Column('styleName', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['artistName'], ['artists.artistName'], ),
    sa.ForeignKeyConstraint(['styleName'], ['styles.styleName'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artStyles')
    # ### end Alembic commands ###
