"""empty message

Revision ID: e0fdf8137071
Revises: 0ba765ce34bb
Create Date: 2019-05-16 16:01:02.567468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0fdf8137071'
down_revision = '0ba765ce34bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artStyles',
    sa.Column('artistName', sa.String(length=120), nullable=False),
    sa.Column('styleName', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['artistName'], ['artists.artistName'], onupdate='cascade'),
    sa.ForeignKeyConstraint(['styleName'], ['styles.styleName'], onupdate='cascade'),
    sa.PrimaryKeyConstraint('artistName', 'styleName')
    )
    op.create_table('artistPreferences',
    sa.Column('customerName', sa.String(length=120), nullable=False),
    sa.Column('artistName', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['artistName'], ['artists.artistName'], onupdate='cascade'),
    sa.ForeignKeyConstraint(['customerName'], ['customers.customerName'], onupdate='cascade'),
    sa.PrimaryKeyConstraint('customerName', 'artistName')
    )
    op.create_table('groupPreferences',
    sa.Column('customerName', sa.String(length=120), nullable=False),
    sa.Column('groupName', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['customerName'], ['customers.customerName'], onupdate='cascade'),
    sa.ForeignKeyConstraint(['groupName'], ['groups.groupName'], onupdate='cascade'),
    sa.PrimaryKeyConstraint('customerName', 'groupName')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groupPreferences')
    op.drop_table('artistPreferences')
    op.drop_table('artStyles')
    # ### end Alembic commands ###
