"""empty message

Revision ID: e6d1ef7a431f
Revises: 9b976e6dc8af
Create Date: 2019-05-11 21:00:49.956030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d1ef7a431f'
down_revision = '9b976e6dc8af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artistPreferences',
    sa.Column('customerName', sa.String(length=120), nullable=True),
    sa.Column('artistName', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['artistName'], ['artists.artistName'], ),
    sa.ForeignKeyConstraint(['customerName'], ['customers.customerName'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artistPreferences')
    # ### end Alembic commands ###
