"""empty message

Revision ID: ef99d3d704d2
Revises: bdfa6b92ae46
Create Date: 2019-05-08 09:13:27.666941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef99d3d704d2'
down_revision = 'bdfa6b92ae46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupings',
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('groupName', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['groupName'], ['groups.groupName'], ),
    sa.ForeignKeyConstraint(['title'], ['artwork.title'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groupings')
    # ### end Alembic commands ###
