"""empty message

Revision ID: f292fa78130f
Revises: 
Create Date: 2019-05-05 22:44:28.444872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f292fa78130f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('artistName', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('birthplace', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('artistName')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customerName', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('expenditure', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customerName'),
    sa.UniqueConstraint('email')
    )
    op.create_table('groups',
    sa.Column('groupName', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('groupName')
    )
    op.create_table('styles',
    sa.Column('styleName', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('styleName')
    )
    op.create_table('artStyles',
    sa.Column('artistName', sa.String(length=120), nullable=True),
    sa.Column('styleName', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['artistName'], ['artists.artistName'], ),
    sa.ForeignKeyConstraint(['styleName'], ['styles.styleName'], )
    )
    op.create_table('artistPreferences',
    sa.Column('customerName', sa.String(length=120), nullable=True),
    sa.Column('artistName', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['artistName'], ['artists.artistName'], ),
    sa.ForeignKeyConstraint(['customerName'], ['customers.customerName'], )
    )
    op.create_table('artwork',
    sa.Column('artistName', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('typeOfArt', sa.String(length=60), nullable=False),
    sa.Column('purchased', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['artistName'], ['artists.artistName'], ),
    sa.ForeignKeyConstraint(['purchased'], ['customers.customerName'], ),
    sa.PrimaryKeyConstraint('title')
    )
    op.create_index(op.f('ix_artwork_title'), 'artwork', ['title'], unique=False)
    op.create_table('groupPreferences',
    sa.Column('customerName', sa.String(length=120), nullable=True),
    sa.Column('groupName', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['customerName'], ['customers.customerName'], ),
    sa.ForeignKeyConstraint(['groupName'], ['groups.groupName'], )
    )
    op.create_table('grouping',
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('groupName', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['groupName'], ['groups.groupName'], ),
    sa.ForeignKeyConstraint(['title'], ['artwork.title'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grouping')
    op.drop_table('groupPreferences')
    op.drop_index(op.f('ix_artwork_title'), table_name='artwork')
    op.drop_table('artwork')
    op.drop_table('artistPreferences')
    op.drop_table('artStyles')
    op.drop_table('styles')
    op.drop_table('groups')
    op.drop_table('customers')
    op.drop_table('artists')
    # ### end Alembic commands ###
