"""empty message

Revision ID: f311e01059eb
Revises: deb1407115f6
Create Date: 2019-05-10 09:57:09.432019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f311e01059eb'
down_revision = 'deb1407115f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'artstyles_ibfk_2', 'artStyles', type_='foreignkey')
    op.drop_constraint(u'artstyles_ibfk_1', 'artStyles', type_='foreignkey')
    op.create_foreign_key(None, 'artStyles', 'artists', ['artistName'], ['artistName'], onupdate='cascade')
    op.create_foreign_key(None, 'artStyles', 'styles', ['styleName'], ['styleName'], onupdate='cascade')
    op.drop_constraint(u'artwork_ibfk_1', 'artwork', type_='foreignkey')
    op.create_foreign_key(None, 'artwork', 'artists', ['artistName'], ['artistName'], onupdate='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artwork', type_='foreignkey')
    op.create_foreign_key(u'artwork_ibfk_1', 'artwork', 'artists', ['artistName'], ['artistName'])
    op.drop_constraint(None, 'artStyles', type_='foreignkey')
    op.drop_constraint(None, 'artStyles', type_='foreignkey')
    op.create_foreign_key(u'artstyles_ibfk_1', 'artStyles', 'artists', ['artistName'], ['artistName'])
    op.create_foreign_key(u'artstyles_ibfk_2', 'artStyles', 'styles', ['styleName'], ['styleName'])
    # ### end Alembic commands ###
